version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bootstrap-configuration"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-631xllnkw1g6"
s3_prefix = "bootstrap-configuration"
region = "eu-west-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "GitHubOwner=\"iot-cloud-system-final-assignment-mc\" GitHubRepo=\"bootstrap-configuration\" GitHubBranch=\"main\" ApplicationStackName=\"bootstrap-configuration\""
image_repositories = []
