version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bootstrap-resources"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11otlm1qgtcw0"
s3_prefix = "bootstrap-resources"
region = "eu-west-1"
capabilities = "CAPABILITY_AUTO_EXPAND"
image_repositories = []
