AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Iot-Cloud-Systems Final Assignment - Marco Cavalli

Parameters:
  AdminEmailParameter:
    Type: String
    Description: "Enter the System Administrator email address"
  ApiKeyAdminParameter:
    Type: String
    Default: "9a7743fa-3ae7-11eb-adc1-0242ac120002"
    Description: "Enter default API key value to be used by API Gateway for System Administrators"
  ApiKeyUserParameter:
    Type: String
    Default: "88b43c36-802e-11eb-af35-38f9d35b2c15"
    Description: "Enter default API key value to be used by API Gateway for normal Users"

Resources:
  DynamoDBTables:
    Type: AWS::Serverless::Application
    Properties:
      Location: nested_templates/dynamodb.yml

  WebsiteHosting:
    Type: AWS::Serverless::Application
    Properties:
      Location: nested_templates/website_hosting.yml

  Cognito:
    DependsOn: WebsiteHosting
    Type: AWS::Serverless::Application
    Properties:
      Location: nested_templates/cognito.yml
      Parameters:
        AdminEmailParameter: !Ref AdminEmailParameter
        ApiKeyAdminParameter: !Ref ApiKeyAdminParameter
        UserPoolCallbackURLParameter: !GetAtt WebsiteHosting.Outputs.ApplicationSite

  UtilsLayers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: utils-layer
      Description: Utilities for project
      ContentUri: ./layers
      CompatibleRuntimes:
        - nodejs14.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

Outputs:
  ApplicationSiteBucket:
    Description: The S3 Bucket that will contain the static assets for the application
    Value: !GetAtt WebsiteHosting.Outputs.AppBucket
    Export:
      Name: "Cloud-Systems-IoT-ApplicationSiteBucket"
  ApplicationSite:
    Description: The name of the CloudFront url for the application site
    Value: !GetAtt WebsiteHosting.Outputs.ApplicationSite
    Export:
      Name: "Cloud-Systems-IoT-ApplicationSite"  
  CognitoUserPoolId:
    Description: The ID of the Cognito User Pool
    Value: !GetAtt Cognito.Outputs.CognitoUserPoolId
    Export:
      Name: "Cloud-Systems-IoT-CognitoUserPoolId"
  CognitoUserPoolClientId:
    Description: The ID of the Cognito User Pool Client
    Value: !GetAtt Cognito.Outputs.CognitoUserPoolClientId
    Export:
      Name: "Cloud-Systems-IoT-CognitoUserPoolClientId"
  CognitoUserPoolProviderURL:
    Description: The URL of the Cognito User Pool Provider
    Value: !GetAtt Cognito.Outputs.CognitoUserPoolProviderURL
    Export:
      Name: "Cloud-Systems-IoT-CognitoUserPoolProviderURL"
  UtilsLayerArn:
    Description: The ARN of the HttpUtilsLayer
    Value: !Ref UtilsLayers
    Export:
      Name: "Cloud-Systems-IoT-HttpUtilsLayerArn"